name: a

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Start SSH session (via sshx.io)
        run: |
          curl -sSf https://sshx.io/get | sh
